spring:
  redis:
    host: localhost
    port: 6379
    password: 12345678
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fox_edge?useUnicode=true&characterEncoding=utf8
    username: fox-edge
    password: 12345678
    # 初始化时建立的物理连接数。初始化发生在显式调用init方法，或者第一次getConnection时.
    initial-size: 1
    # 连接池最大物理连接数量。
    max-active: 3
    # 连接池最小物理连接数量。
    min-idle: 1

  fox-service:                      # 配置信息
    service:                        # 服务信息，指明这个服务的模块信息，用于识别进程，它跟shell和restful路由强相关
      type: "system"                # 服务类型：kernel/system/service
      name: "persist-service"       # 服务名称：这是服务的名称
    model:                          # 模块信息，用于业务之间的分类和协助
      type: "persist"               # 模块类型，指明这是一个controller类型的业务，这类业务主要是用户的业务流程的逻辑
      name: "persist"        # 模块类型名称，告知别的业务，它的业务名称，可以通过该名称跟它进行通信，比如topic的主题

  redis_topic:
    controller_model: "system_controller"