spring:
  application:
    name: fox-edge-server-channel-proxy-server


  redis_topic:
    # 公共的channel级的topic，各channel的响应数据会发送到这边，所有最好只有一个订阅者，比如设备适配器
    # 并且需要打上UUID来识别报文的对应关系
    subscriber_channel_topic: "topic_channel_respond"

  fox-service:                            # 配置信息
    service:                              # 服务信息，指明这个服务的模块信息，用于识别进程，它跟shell和restful路由强相关
      type: "service"                     # 服务类型：kernel/system/service
      name: "channel-proxy-server"        # 服务名称：这是服务的名称
    model:                                # 模块信息，用于业务之间的分类和协助
      type: "proxy"                       # 模块类型，指明这是一个controller类型的业务，这类业务主要是用户的业务流程的逻辑
      name: "proxy-server"                # 模块类型名称，告知别的业务，它的业务名称，可以通过该名称跟它进行通信，比如topic的主题

  redis:
    host: localhost
    port: 6379
    password: 12345678
    jedis:
      pool:
        max-active: 200 #最大连接数
        max-wait: -1    #最大等待阻塞时间
        max-idle: 10    #最大空闲连接
        min-idle: 0     #最小空闲时间
    timeout: 10000000     #连接超时时间


