spring:
  redis:
    host: localhost
    port: 6379
    password: 12345678

  cloud:
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 系统模块
        - id: fox-edge-server-manager-system-service
          uri: lb://fox-edge-server-manager-system-service
          predicates:
            - Path=/kernel/manager/**
          filters:
            - StripPrefix=2


  fox-service: # 配置信息
    service: # 服务信息，指明这个服务的模块信息，用于识别进程，它跟shell和restful路由强相关
      type: "kernel"                # 服务类型：kernel/system/service
      name: "gateway-service"       # 服务名称：这是服务的名称
    model: # 模块信息，用于业务之间的分类和协助
      type: "gateway"               # 模块类型，指明这是一个controller类型的业务，这类业务主要是用户的业务流程的逻辑
      name: "gateway"               # 模块类型名称，告知别的业务，它的业务名称，可以通过该名称跟它进行通信，比如topic的主题

sa-token: # jwt秘钥
  jwt-secret-key: aasdasdasifhueuiwyusrfewbfjsdafjk