# 开发环境配置
server:
  port: 9201

spring:
  application:
    name: fox-edge-server-device-service

  redis:
    host: localhost
    port: 6379
    password: 12345678
    jedis:
      pool:
        max-active: 200 #最大连接数
        max-wait: -1    #最大等待阻塞时间
        max-idle: 10    #最大空闲连接
        min-idle: 0     #最小空闲时间
    timeout: 10000000     #连接超时时间
